### ISSUE TITLE
Day 3

### ISSUE THREAD

**Issue by lanfeng0706** [Nododo/Swift_100days#1]
运行起来和gif效果图不一致。

**Comment by Nododo** [comment]
能具体点吗?

**Comment by lanfeng0706** [comment]
你可以试着运行下Day3的工程，数据方面应该是有点问题，didSet里面的没有调用，还有TextField的Action事件拖动也是没有反应的。你试着运行看下就知道啦。

**Comment by Nododo** [comment]
我这边没问题啊  你确定顶上topField有值吗?

**Comment by lanfeng0706** [comment]
恩，TopField刚才是忘记输入值了。还有一个疑问请教下：init方法设置的初始化值在Label上没有显示，Label的值是在拖拽的UISlider的时候才更新的。

**Comment by Nododo** [comment]
没怎么看懂   因为拖拽的UISlider时候才赋值的

**Comment by lanfeng0706** [comment]
tipModel = TipModel.init(tipCount: "15%", topPrice: "$0.00", totalPrice: "0.00") 
这句话中设置的数字，实际在关于Label初始化显示的时候，应该是没有起到作用吧。因为didSet方法应该是在拖拽UISlider时候赋值，然后才Label的值才更新的。

**Comment by Nododo** [comment]
是的

**Comment by lanfeng0706** [comment]
好的。谢谢啦。刚开始学Swift，有的问题比较浅显，见谅哈。谢谢你的耐心解答。

**Comment by Nododo** [comment]
有闲暇时间就会解答的,我也是刚开始学,共勉~
