### ISSUE TITLE
27day、28day,cell没注册，就没有复用

### ISSUE THREAD

**Issue by leibaozai** [Nododo/Swift_100days#2]
func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
         return 30;
}

func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if  let cell: UITableViewCell = tableView.dequeueReusableCell(withIdentifier: "table") {
            cell.textLabel?.text = "movie name"
            return cell
        } else {
            let cell = UITableViewCell()
            cell.textLabel?.text = "movie name create"
            return cell
        }
    }

这里只有从注册列表去取，并没有在初始化注册，在else这里应该改为如下
        } else {
            let cell = UITableViewCell(style: .default, reuseIdentifier: "table")
            cell.textLabel?.text = "movie name create"
            return cell
        }

**Comment by Nododo** [comment]
sorry  这里如果注册了就应该取到 else 是没用的
如果是swift 3.0了  建议你去看官方文档，这些小demo仅做参考吧~

https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/TheBasics.html#//apple_ref/doc/uid/TP40014097-CH5-ID309
